### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by Rstacx** [tszhong0411/one-blog#2]
There is a build error 

```
Failed to compile.
--
23:17:30.454 |  
23:17:30.455 | ./src/app/me/settings/form.tsx:44:5
23:17:30.455 | Type error: Type 'Resolver<{ bio?: string \| undefined; image: string; name: string; }>' is not assignable to type 'Resolver<Values, any>'.
23:17:30.455 | Types of parameters 'options' and 'options' are incompatible.
23:17:30.455 | Type 'ResolverOptions<Values>' is not assignable to type 'ResolverOptions<{ bio?: string \| undefined; image: string; name: string; }>'.
23:17:30.455 | Type '{ bio?: string \| undefined; image: string; name: string; }' is not assignable to type 'Values'.
23:17:30.455 |  
23:17:30.455 | 42 \|     formState: { errors },
23:17:30.456 | 43 \|   } = useForm<Values>({
23:17:30.456 | > 44 \|     resolver: yupResolver(settingsSchema),
23:17:30.456 | \|     ^
23:17:30.456 | 45 \|     defaultValues: {
23:17:30.456 | 46 \|       image: image as string,
23:17:30.456 | 47 \|       name: name as string,
23:17:30.606 | Error: Command "npm run build" exited with 1

**Comment by nelsonlaidev** [comment]
There is no build error on my machine. Did you do anything extra?

<img width="962" alt="image" src="https://github.com/tszhong0411/one-blog/assets/75498339/0ce657c7-1d27-4f45-bffa-fc186715892f">

**Comment by Rstacx** [comment]
> There is no build error on my machine. Did you do anything extra?
> 
> <img alt="image" width="962" src="https://user-images.githubusercontent.com/75498339/265223135-0ce657c7-1d27-4f45-bffa-fc186715892f.png">

I went to deploy from vercel but this error is coming 
I tried to build from vps and localhost but this error is coming 
![Screenshot_20230903-013831_JuiceSSH](https://github.com/tszhong0411/one-blog/assets/107676259/63d785bb-6711-4206-baec-ad7c9117ee4a)

**Comment by Rstacx** [comment]
Fixed the issue
